### PR TITLE
Remove coffe script from the example

### PR DESCRIPTION
**Pull request by piercus**
Hello,

While testing the example, i had 2 errors : 
1. Some parts of the javascript was written in coffee script
1. I used a wrong sample rate 

In order to help, I have corrected 1, and added a more explicit error message for 2.

Please share your concerns of this, if any.

Thank you for your library

### CODE REVIEW

**Comment by patlevin** [comment]
The sample code is not Coffeescript, but in fact perfectly valid ES6. The supported sample rates might change in the future, so I'd rather not include any restrictions at this point.

**Comment by piercus** [comment]
My node version is not supporting it, can you please tell me which node version are you using ?

```
 $ node waveform-generator.js 
/home/pierre/dev/voixen-vad/examples/waveform/waveform-generator.js:75
    const { r = r, g = g, b = b, a = a } = colour
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
[1]    1925 exit 1     node waveform-generator.js
$ node -v
v4.4.7
```

**Comment by patlevin** [comment]
I use the LTS version, which is currently v6.9.1. Support for v4.x and older has pretty much ceased by now. I can add alternative sample code for v4.6.2, though, since that's the oldest version I have have currently installed.

Cheers

**Comment by piercus** [comment]
Thank you for your help i'm switching to v6

**Pull request closed without merging**
